name: project pipeline CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Navigate to the project folder
      - name: Change directory to project folder
        run: cd my_project

      # Step 3: Make the tests.sh script executable
      - name: Make tests.sh executable
        run: chmod +x project/tests.sh

      # Step 4: Run the tests
      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: project/tests.sh
