name: Project-feedback (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r project/requirements.txt

      # Step 4: Ensure tests.sh is executable
      - name: Ensure tests.sh is executable
        run: chmod +x ./project/tests.sh

      # Step 5: Run tests.sh
      - name: Run tests
        run: ./project/tests.sh
